[workspace]
members = [
    "crates/bench",
    "crates/cli",
    "crates/config",
    "crates/control",
    "crates/core",
    "crates/integration",
    "crates/io-afpacket",
    "crates/io-conformance",
    "crates/io-dpdk",
    "crates/io-sim",
    "crates/io-xdp",
    "crates/io-xdp-native",
    "crates/runtime",
    "crates/sim-scenario",
]
resolver = "2"

[workspace.package]
edition = "2021"
version = "0.2.0"
license = "MIT OR Apache-2.0"
publish = false
