//! ICMPv6 error message generation for the ruster dataplane.
//!
//! When the router drops an IPv6 packet due to Hop Limit expiration or
//! unreachable destination, it generates an ICMPv6 error message back to
//! the original sender per RFC 4443.
//!
//! RFC-REF: RFC 4443 Section 2
//! "ICMPv6 is used by IPv6 nodes to report errors encountered in
//! processing packets, and to perform other internet-layer functions."
//!
//! # Loop prevention
//!
//! RFC-REF: RFC 4443 Section 2.4
//! "An ICMPv6 error message MUST NOT be originated as a result of
//! receiving [...] An ICMPv6 error message."
//! We suppress ICMPv6 error generation when the original packet is itself
//! an ICMPv6 error message (type < 128) to prevent infinite loops.
//!
//! # Multicast suppression
//!
//! RFC-REF: RFC 4443 Section 2.4
//! "An ICMPv6 error message MUST NOT be originated as a result of
//! receiving a packet destined to an IPv6 multicast address."
//! (Exception: Packet Too Big -- not relevant here.)

use crate::icmp::IcmpReply;

/// ICMPv6 error types that can be generated by the router.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Icmpv6Error {
    /// Time Exceeded: Hop Limit exceeded in transit.
    ///
    /// RFC-REF: RFC 4443 Section 3.3
    /// Type = 3, Code = 0: hop limit exceeded in transit.
    HopLimitExceeded,

    /// Destination Unreachable: no route to destination.
    ///
    /// RFC-REF: RFC 4443 Section 3.1
    /// Type = 1, Code = 0: no route to destination.
    NoRoute,
}

impl Icmpv6Error {
    /// Return the (type, code) pair for this ICMPv6 error.
    fn type_code(&self) -> (u8, u8) {
        match self {
            Icmpv6Error::HopLimitExceeded => (3, 0),
            Icmpv6Error::NoRoute => (1, 0),
        }
    }
}

// ── Constants ───────────────────────────────────────────────────────

/// Minimum Ethernet header size.
const ETH_HEADER_LEN: usize = 14;

/// Fixed IPv6 header size.
const IPV6_HEADER_LEN: usize = 40;

/// ICMPv6 header size: type(1) + code(1) + checksum(2) + unused(4) = 8.
const ICMPV6_HEADER_LEN: usize = 8;

/// EtherType for IPv6.
const ETHERTYPE_IPV6: u16 = 0x86DD;

/// IPv6 Next Header value for ICMPv6.
const NEXT_HEADER_ICMPV6: u8 = 58;

/// Hop Limit for generated ICMPv6 error packets.
const ICMPV6_ERROR_HOP_LIMIT: u8 = 64;

/// Minimum IPv6 MTU per RFC 8200 Section 5.
///
/// RFC-REF: RFC 8200 Section 5
/// "IPv6 requires that every link in the Internet have an MTU of
/// 1280 octets or greater."
const IPV6_MINIMUM_MTU: usize = 1280;

/// Minimum original packet length needed to generate an ICMPv6 error:
/// Ethernet(14) + IPv6(40) = 54 bytes.
const MIN_ORIGINAL_PACKET_LEN: usize = ETH_HEADER_LEN + IPV6_HEADER_LEN;

// ── Public API ──────────────────────────────────────────────────────

/// Generate an ICMPv6 error message in response to a dropped IPv6 packet.
///
/// The generated packet includes:
/// - Swapped Ethernet MACs (reply goes back towards the sender)
/// - New IPv6 header (src = `router_ipv6`, dst = original src IPv6, hop limit = 64)
/// - ICMPv6 header (type/code from `error`, checksum computed, 4 unused bytes)
/// - As much of the invoking packet as possible without exceeding the
///   minimum IPv6 MTU (1280 bytes)
///
/// RFC-REF: RFC 4443 Section 2.4
/// "Every ICMPv6 error message includes as much of the IPv6 offending
/// (invoking) packet as possible without the ICMPv6 packet exceeding
/// the minimum IPv6 MTU."
///
/// Returns `None` if:
/// - The original packet is too short (< 54 bytes: 14 Ethernet + 40 IPv6)
/// - The original packet is not IPv6
/// - The original packet is an ICMPv6 error message (loop prevention per RFC 4443)
/// - The original packet destination is a multicast address (RFC 4443)
pub fn generate_icmpv6_error(
    original_packet: &[u8],
    error: Icmpv6Error,
    router_ipv6: [u8; 16],
    egress_iface: &str,
) -> Option<IcmpReply> {
    // ── Validate original packet ────────────────────────────────────
    if original_packet.len() < MIN_ORIGINAL_PACKET_LEN {
        return None;
    }

    // Check EtherType is IPv6.
    let ethertype = u16::from_be_bytes([original_packet[12], original_packet[13]]);
    if ethertype != ETHERTYPE_IPV6 {
        return None;
    }

    // Extract original IPv6 header fields.
    let orig_ipv6 = &original_packet[ETH_HEADER_LEN..];
    let orig_version = orig_ipv6[0] >> 4;
    if orig_version != 6 {
        return None;
    }

    let orig_next_header = orig_ipv6[6];

    // RFC-REF: RFC 4443 Section 2.4
    // "An ICMPv6 error message MUST NOT be originated as a result of
    // receiving [...] An ICMPv6 error message."
    // ICMPv6 error messages have type values < 128.
    if orig_next_header == NEXT_HEADER_ICMPV6 {
        // Check if there's enough data to read the ICMPv6 type byte.
        let icmpv6_offset = ETH_HEADER_LEN + IPV6_HEADER_LEN;
        if original_packet.len() > icmpv6_offset {
            let icmpv6_type = original_packet[icmpv6_offset];
            if icmpv6_type < 128 {
                // This is an ICMPv6 error message; suppress to prevent loops.
                return None;
            }
        }
    }

    // Extract original source IPv6 address (this becomes the ICMPv6 reply destination).
    let mut orig_src_ipv6 = [0u8; 16];
    orig_src_ipv6.copy_from_slice(&orig_ipv6[8..24]);

    // Extract original destination IPv6 address for multicast check.
    let orig_dst_ipv6_first_byte = orig_ipv6[24];

    // RFC-REF: RFC 4443 Section 2.4
    // "An ICMPv6 error message MUST NOT be originated as a result of
    // receiving a packet destined to an IPv6 multicast address."
    // (Exception: Packet Too Big and Parameter Problem Code 2 -- not applicable here.)
    // IPv6 multicast addresses start with 0xFF.
    if orig_dst_ipv6_first_byte == 0xFF {
        return None;
    }

    // ── Build the ICMPv6 payload ──────────────────────────────────
    // RFC-REF: RFC 4443 Section 2.4
    // "Every ICMPv6 error message [...] includes as much of the IPv6
    // offending (invoking) packet [...] without the ICMPv6 packet
    // exceeding the minimum IPv6 MTU [1280 bytes]."
    //
    // The ICMPv6 packet structure:
    //   IPv6 header (40) + ICMPv6 header (8) + invoking packet data
    // Total must not exceed 1280 bytes.
    // So: invoking_data_max = 1280 - 40 - 8 = 1232 bytes.
    let max_invoking_data = IPV6_MINIMUM_MTU - IPV6_HEADER_LEN - ICMPV6_HEADER_LEN;
    let avail_invoking_data = original_packet.len() - ETH_HEADER_LEN;
    let invoking_data_len = avail_invoking_data.min(max_invoking_data);
    let invoking_data = &orig_ipv6[..invoking_data_len];

    // ── Build the reply packet ──────────────────────────────────────
    let icmpv6_total_len = ICMPV6_HEADER_LEN + invoking_data_len;
    let ipv6_payload_len = icmpv6_total_len as u16;
    let total_frame_len = ETH_HEADER_LEN + IPV6_HEADER_LEN + icmpv6_total_len;

    let mut pkt = Vec::with_capacity(total_frame_len);

    // ── Ethernet header (swapped MACs) ──────────────────────────────
    // dst MAC = original src MAC (reply back to sender)
    pkt.extend_from_slice(&original_packet[6..12]);
    // src MAC = original dst MAC (our interface MAC)
    pkt.extend_from_slice(&original_packet[0..6]);
    // EtherType: IPv6
    pkt.extend_from_slice(&ETHERTYPE_IPV6.to_be_bytes());

    // ── IPv6 header ─────────────────────────────────────────────────
    // Version=6, Traffic Class=0, Flow Label=0
    pkt.extend_from_slice(&[0x60, 0x00, 0x00, 0x00]);
    // Payload Length
    pkt.extend_from_slice(&ipv6_payload_len.to_be_bytes());
    // Next Header: ICMPv6 (58)
    pkt.push(NEXT_HEADER_ICMPV6);
    // Hop Limit
    pkt.push(ICMPV6_ERROR_HOP_LIMIT);
    // Source Address: router IPv6
    pkt.extend_from_slice(&router_ipv6);
    // Destination Address: original source IPv6
    pkt.extend_from_slice(&orig_src_ipv6);

    // ── ICMPv6 header ───────────────────────────────────────────────
    let (icmpv6_type, icmpv6_code) = error.type_code();
    let icmpv6_start = pkt.len();
    pkt.push(icmpv6_type);
    pkt.push(icmpv6_code);
    pkt.extend_from_slice(&[0x00, 0x00]); // checksum placeholder
    pkt.extend_from_slice(&[0x00, 0x00, 0x00, 0x00]); // 4 unused bytes

    // ── ICMPv6 payload (invoking packet data) ───────────────────────
    pkt.extend_from_slice(invoking_data);

    // ── Compute ICMPv6 checksum ─────────────────────────────────────
    // RFC-REF: RFC 4443 Section 2.3
    // "The checksum is the 16-bit one's complement of the one's complement
    // sum of the entire ICMPv6 message, starting with the ICMPv6 message
    // type field, and prepended with a 'pseudo-header' [...]"
    let icmpv6_msg = &pkt[icmpv6_start..];
    let checksum = compute_icmpv6_checksum(&router_ipv6, &orig_src_ipv6, icmpv6_msg);
    pkt[icmpv6_start + 2] = (checksum >> 8) as u8;
    pkt[icmpv6_start + 3] = (checksum & 0xFF) as u8;

    Some(IcmpReply {
        egress_iface: egress_iface.to_string(),
        data: pkt,
    })
}

// ── Checksum helpers ────────────────────────────────────────────────

/// Compute the ICMPv6 checksum per RFC 4443 Section 2.3.
///
/// The checksum covers a pseudo-header (src IPv6, dst IPv6, upper-layer
/// packet length, next header = 58) plus the ICMPv6 message body.
///
/// RFC-REF: RFC 2460 Section 8.1
/// "The IPv6 version of ICMP [...] includes the IPv6 pseudo-header
/// [...] in its checksum computation."
fn compute_icmpv6_checksum(src_ipv6: &[u8; 16], dst_ipv6: &[u8; 16], icmpv6_data: &[u8]) -> u16 {
    let mut sum: u32 = 0;

    // Pseudo-header: source address (16 bytes)
    for i in (0..16).step_by(2) {
        sum += u16::from_be_bytes([src_ipv6[i], src_ipv6[i + 1]]) as u32;
    }
    // Pseudo-header: destination address (16 bytes)
    for i in (0..16).step_by(2) {
        sum += u16::from_be_bytes([dst_ipv6[i], dst_ipv6[i + 1]]) as u32;
    }
    // Pseudo-header: upper-layer packet length (4 bytes)
    let length = icmpv6_data.len() as u32;
    sum += length >> 16;
    sum += length & 0xFFFF;
    // Pseudo-header: next header = 58 (ICMPv6)
    sum += 58u32;

    // ICMPv6 message body
    let mut i = 0;
    while i + 1 < icmpv6_data.len() {
        sum += u16::from_be_bytes([icmpv6_data[i], icmpv6_data[i + 1]]) as u32;
        i += 2;
    }
    if i < icmpv6_data.len() {
        sum += (icmpv6_data[i] as u32) << 8;
    }

    // Fold 32-bit sum to 16 bits
    while (sum >> 16) != 0 {
        sum = (sum & 0xFFFF) + (sum >> 16);
    }

    !(sum as u16)
}

// ── Tests ───────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    /// Router's IPv6 address for testing.
    const ROUTER_IPV6: [u8; 16] = [
        0x20, 0x01, 0x0d, 0xb8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0x01,
    ];

    /// Build a valid Ethernet + IPv6 + UDP packet for testing.
    fn make_test_ipv6_packet(
        src_mac: [u8; 6],
        dst_mac: [u8; 6],
        src_ipv6: [u8; 16],
        dst_ipv6: [u8; 16],
        hop_limit: u8,
        next_header: u8,
    ) -> Vec<u8> {
        let mut pkt = Vec::new();
        // Ethernet header (14 bytes)
        pkt.extend_from_slice(&dst_mac);
        pkt.extend_from_slice(&src_mac);
        pkt.extend_from_slice(&[0x86, 0xDD]); // EtherType IPv6

        // IPv6 header (40 bytes)
        pkt.push(0x60); // Version=6, TC=0
        pkt.push(0x00);
        pkt.push(0x00);
        pkt.push(0x00);
        // Payload Length = 8 (UDP header)
        pkt.extend_from_slice(&8u16.to_be_bytes());
        pkt.push(next_header);
        pkt.push(hop_limit);
        pkt.extend_from_slice(&src_ipv6);
        pkt.extend_from_slice(&dst_ipv6);

        // Minimal payload (8 bytes -- e.g., UDP header)
        pkt.extend_from_slice(&[0x00, 0x50]); // src port: 80
        pkt.extend_from_slice(&[0x00, 0x51]); // dst port: 81
        pkt.extend_from_slice(&[0x00, 0x08]); // length: 8
        pkt.extend_from_slice(&[0x00, 0x00]); // checksum: 0

        pkt
    }

    /// Verify the ICMPv6 checksum (including pseudo-header) is valid.
    fn verify_icmpv6_checksum(src_ipv6: &[u8; 16], dst_ipv6: &[u8; 16], icmpv6_msg: &[u8]) -> bool {
        let mut sum: u32 = 0;
        // Pseudo-header
        for i in (0..16).step_by(2) {
            sum += u16::from_be_bytes([src_ipv6[i], src_ipv6[i + 1]]) as u32;
        }
        for i in (0..16).step_by(2) {
            sum += u16::from_be_bytes([dst_ipv6[i], dst_ipv6[i + 1]]) as u32;
        }
        let length = icmpv6_msg.len() as u32;
        sum += length >> 16;
        sum += length & 0xFFFF;
        sum += 58u32;

        // ICMPv6 message body (including checksum field)
        let mut i = 0;
        while i + 1 < icmpv6_msg.len() {
            sum += u16::from_be_bytes([icmpv6_msg[i], icmpv6_msg[i + 1]]) as u32;
            i += 2;
        }
        if i < icmpv6_msg.len() {
            sum += (icmpv6_msg[i] as u32) << 8;
        }

        while (sum >> 16) != 0 {
            sum = (sum & 0xFFFF) + (sum >> 16);
        }
        sum as u16 == 0xFFFF
    }

    // ── Hop Limit Exceeded tests ──────────────────────────────────

    #[test]
    fn hop_limit_exceeded_generates_icmpv6() {
        let src_mac = [0xAA, 0xBB, 0xCC, 0xDD, 0xEE, 0xFF];
        let dst_mac = [0x00, 0x11, 0x22, 0x33, 0x44, 0x55];
        let src_ipv6 = [
            0x20, 0x01, 0x0d, 0xb8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0x64,
        ];
        let dst_ipv6 = [
            0x20, 0x01, 0x0d, 0xb8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0x02,
        ];

        let original = make_test_ipv6_packet(src_mac, dst_mac, src_ipv6, dst_ipv6, 1, 17);
        let reply = generate_icmpv6_error(
            &original,
            Icmpv6Error::HopLimitExceeded,
            ROUTER_IPV6,
            "lan0",
        )
        .expect("should generate ICMPv6 reply");

        assert_eq!(reply.egress_iface, "lan0");

        let data = &reply.data;

        // Check Ethernet header: MACs are swapped.
        assert_eq!(&data[0..6], &src_mac); // dst = original src
        assert_eq!(&data[6..12], &dst_mac); // src = original dst
        assert_eq!(&data[12..14], &[0x86, 0xDD]); // EtherType IPv6

        // Check IPv6 header.
        let ipv6 = &data[ETH_HEADER_LEN..ETH_HEADER_LEN + IPV6_HEADER_LEN];
        assert_eq!(ipv6[0] >> 4, 6); // version=6
        assert_eq!(ipv6[6], NEXT_HEADER_ICMPV6); // next_header = ICMPv6
        assert_eq!(ipv6[7], ICMPV6_ERROR_HOP_LIMIT); // hop_limit = 64
        assert_eq!(&ipv6[8..24], &ROUTER_IPV6); // src = router IPv6
        assert_eq!(&ipv6[24..40], &src_ipv6); // dst = original src IPv6

        // Check ICMPv6 header.
        let icmpv6_start = ETH_HEADER_LEN + IPV6_HEADER_LEN;
        assert_eq!(data[icmpv6_start], 3); // Type: Time Exceeded
        assert_eq!(data[icmpv6_start + 1], 0); // Code: 0

        // ICMPv6 payload should contain the invoking packet (IPv6 header + payload).
        let icmpv6_payload_start = icmpv6_start + ICMPV6_HEADER_LEN;
        let expected_payload = &original[ETH_HEADER_LEN..];
        assert_eq!(
            &data[icmpv6_payload_start..icmpv6_payload_start + expected_payload.len()],
            expected_payload
        );
    }

    #[test]
    fn no_route_generates_icmpv6() {
        let src_ipv6 = [
            0x20, 0x01, 0x0d, 0xb8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0x05,
        ];
        let dst_ipv6 = [
            0x20, 0x01, 0x0d, 0xb8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0x99,
        ];

        let original = make_test_ipv6_packet([0xAA; 6], [0xBB; 6], src_ipv6, dst_ipv6, 64, 17);
        let reply = generate_icmpv6_error(&original, Icmpv6Error::NoRoute, ROUTER_IPV6, "wan0")
            .expect("should generate ICMPv6 reply");

        let icmpv6_start = ETH_HEADER_LEN + IPV6_HEADER_LEN;
        assert_eq!(reply.data[icmpv6_start], 1); // Type: Destination Unreachable
        assert_eq!(reply.data[icmpv6_start + 1], 0); // Code: No Route
        assert_eq!(reply.egress_iface, "wan0");
    }

    // ── Loop prevention tests ───────────────────────────────────────

    #[test]
    fn no_icmpv6_for_icmpv6_error_packets() {
        // RFC-REF: RFC 4443 Section 2.4
        // "An ICMPv6 error message MUST NOT be originated as a result of
        // receiving [...] An ICMPv6 error message."
        let src_ipv6 = [
            0x20, 0x01, 0x0d, 0xb8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0x64,
        ];
        let dst_ipv6 = [
            0x20, 0x01, 0x0d, 0xb8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0x02,
        ];

        // Build an IPv6 packet with ICMPv6 next header (58) and an error type (< 128).
        let mut original = make_test_ipv6_packet([0xAA; 6], [0xBB; 6], src_ipv6, dst_ipv6, 1, 58);
        // Set the ICMPv6 type to Time Exceeded (3) -- an error message.
        original[ETH_HEADER_LEN + IPV6_HEADER_LEN] = 3;

        let result = generate_icmpv6_error(
            &original,
            Icmpv6Error::HopLimitExceeded,
            ROUTER_IPV6,
            "lan0",
        );
        assert!(
            result.is_none(),
            "should not generate ICMPv6 for ICMPv6 error packets"
        );
    }

    #[test]
    fn allow_icmpv6_for_icmpv6_informational_packets() {
        // RFC 4443: ICMPv6 informational messages (type >= 128) are allowed
        // to trigger ICMPv6 error responses.
        let src_ipv6 = [
            0x20, 0x01, 0x0d, 0xb8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0x64,
        ];
        let dst_ipv6 = [
            0x20, 0x01, 0x0d, 0xb8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0x02,
        ];

        // Build an IPv6 packet with ICMPv6 next header (58) and Echo Request (128).
        let mut original = make_test_ipv6_packet([0xAA; 6], [0xBB; 6], src_ipv6, dst_ipv6, 1, 58);
        // Set the ICMPv6 type to Echo Request (128) -- informational.
        original[ETH_HEADER_LEN + IPV6_HEADER_LEN] = 128;

        let result = generate_icmpv6_error(
            &original,
            Icmpv6Error::HopLimitExceeded,
            ROUTER_IPV6,
            "lan0",
        );
        assert!(
            result.is_some(),
            "should generate ICMPv6 for ICMPv6 informational packets"
        );
    }

    // ── Multicast suppression tests ─────────────────────────────────

    #[test]
    fn no_icmpv6_for_multicast_destination() {
        // RFC-REF: RFC 4443 Section 2.4
        let src_ipv6 = [
            0x20, 0x01, 0x0d, 0xb8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0x64,
        ];
        // Multicast destination (ff02::1)
        let dst_ipv6 = [0xFF, 0x02, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0x01];

        let original = make_test_ipv6_packet([0xAA; 6], [0xBB; 6], src_ipv6, dst_ipv6, 1, 17);
        let result = generate_icmpv6_error(
            &original,
            Icmpv6Error::HopLimitExceeded,
            ROUTER_IPV6,
            "lan0",
        );
        assert!(
            result.is_none(),
            "should not generate ICMPv6 for multicast destination packets"
        );
    }

    // ── Short packet tests ──────────────────────────────────────────

    #[test]
    fn no_icmpv6_for_short_packets() {
        // Packet shorter than minimum (14 + 40 = 54 bytes).
        let short_pkt = vec![0u8; 50];
        let result = generate_icmpv6_error(
            &short_pkt,
            Icmpv6Error::HopLimitExceeded,
            ROUTER_IPV6,
            "lan0",
        );
        assert!(
            result.is_none(),
            "should not generate ICMPv6 for short packets"
        );
    }

    #[test]
    fn no_icmpv6_for_exactly_too_short() {
        // Packet of exactly 53 bytes (1 byte short of minimum).
        let pkt = vec![0u8; MIN_ORIGINAL_PACKET_LEN - 1];
        let result = generate_icmpv6_error(&pkt, Icmpv6Error::NoRoute, ROUTER_IPV6, "eth0");
        assert!(result.is_none());
    }

    // ── Non-IPv6 tests ──────────────────────────────────────────────

    #[test]
    fn no_icmpv6_for_non_ipv6() {
        // IPv4 packet (EtherType = 0x0800).
        let mut pkt = Vec::new();
        pkt.extend_from_slice(&[0x00; 6]); // dst
        pkt.extend_from_slice(&[0xAA; 6]); // src
        pkt.extend_from_slice(&[0x08, 0x00]); // EtherType: IPv4
        pkt.extend_from_slice(&[0x00; 40]); // Padding to satisfy length check

        let result =
            generate_icmpv6_error(&pkt, Icmpv6Error::HopLimitExceeded, ROUTER_IPV6, "lan0");
        assert!(
            result.is_none(),
            "should not generate ICMPv6 for non-IPv6 packets"
        );
    }

    // ── Checksum tests ──────────────────────────────────────────────

    #[test]
    fn icmpv6_reply_has_valid_checksum() {
        let src_ipv6 = [
            0x20, 0x01, 0x0d, 0xb8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0x64,
        ];
        let dst_ipv6 = [
            0x20, 0x01, 0x0d, 0xb8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0x02,
        ];

        let original = make_test_ipv6_packet([0xAA; 6], [0xBB; 6], src_ipv6, dst_ipv6, 1, 17);
        let reply = generate_icmpv6_error(
            &original,
            Icmpv6Error::HopLimitExceeded,
            ROUTER_IPV6,
            "lan0",
        )
        .unwrap();

        let icmpv6_start = ETH_HEADER_LEN + IPV6_HEADER_LEN;
        let icmpv6_msg = &reply.data[icmpv6_start..];

        assert!(
            verify_icmpv6_checksum(&ROUTER_IPV6, &src_ipv6, icmpv6_msg),
            "ICMPv6 checksum should be valid"
        );
    }

    #[test]
    fn icmpv6_no_route_has_valid_checksum() {
        let src_ipv6 = [
            0x20, 0x01, 0x0d, 0xb8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0x05,
        ];
        let dst_ipv6 = [
            0x20, 0x01, 0x0d, 0xb8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0x99,
        ];

        let original = make_test_ipv6_packet([0xAA; 6], [0xBB; 6], src_ipv6, dst_ipv6, 64, 17);
        let reply =
            generate_icmpv6_error(&original, Icmpv6Error::NoRoute, ROUTER_IPV6, "wan0").unwrap();

        let icmpv6_start = ETH_HEADER_LEN + IPV6_HEADER_LEN;
        let icmpv6_msg = &reply.data[icmpv6_start..];

        assert!(
            verify_icmpv6_checksum(&ROUTER_IPV6, &src_ipv6, icmpv6_msg),
            "ICMPv6 checksum should be valid"
        );
    }

    // ── Frame structure tests ───────────────────────────────────────

    #[test]
    fn icmpv6_reply_total_length_is_correct() {
        let src_ipv6 = [
            0x20, 0x01, 0x0d, 0xb8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0x64,
        ];
        let dst_ipv6 = [
            0x20, 0x01, 0x0d, 0xb8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0x02,
        ];

        let original = make_test_ipv6_packet([0xAA; 6], [0xBB; 6], src_ipv6, dst_ipv6, 1, 17);
        let reply = generate_icmpv6_error(
            &original,
            Icmpv6Error::HopLimitExceeded,
            ROUTER_IPV6,
            "lan0",
        )
        .unwrap();

        // Original invoking data: 40 (IPv6 hdr) + 8 (UDP) = 48 bytes
        // Expected: Ethernet(14) + IPv6(40) + ICMPv6 header(8) + 48 = 110
        let invoking_data_len = original.len() - ETH_HEADER_LEN;
        let expected_len = ETH_HEADER_LEN + IPV6_HEADER_LEN + ICMPV6_HEADER_LEN + invoking_data_len;
        assert_eq!(reply.data.len(), expected_len);

        // Check IPv6 payload length field.
        let ipv6_payload_len = u16::from_be_bytes([
            reply.data[ETH_HEADER_LEN + 4],
            reply.data[ETH_HEADER_LEN + 5],
        ]);
        assert_eq!(
            ipv6_payload_len as usize,
            ICMPV6_HEADER_LEN + invoking_data_len
        );
    }

    #[test]
    fn icmpv6_reply_unused_bytes_are_zero() {
        let src_ipv6 = [
            0x20, 0x01, 0x0d, 0xb8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0x64,
        ];
        let dst_ipv6 = [
            0x20, 0x01, 0x0d, 0xb8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0x02,
        ];

        let original = make_test_ipv6_packet([0xAA; 6], [0xBB; 6], src_ipv6, dst_ipv6, 1, 17);
        let reply = generate_icmpv6_error(
            &original,
            Icmpv6Error::HopLimitExceeded,
            ROUTER_IPV6,
            "lan0",
        )
        .unwrap();

        // The 4 "unused" bytes after the ICMPv6 checksum should all be zero.
        let icmpv6_start = ETH_HEADER_LEN + IPV6_HEADER_LEN;
        assert_eq!(
            &reply.data[icmpv6_start + 4..icmpv6_start + 8],
            &[0x00, 0x00, 0x00, 0x00]
        );
    }

    #[test]
    fn icmpv6_reply_uses_provided_router_ipv6() {
        let router_ip = [
            0x20, 0x01, 0x0d, 0xb8, 0, 0, 0, 0, 0, 0, 0, 0, 0x99, 0x88, 0x77, 0x66,
        ];
        let src_ipv6 = [
            0x20, 0x01, 0x0d, 0xb8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0x64,
        ];
        let dst_ipv6 = [
            0x20, 0x01, 0x0d, 0xb8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0x02,
        ];

        let original = make_test_ipv6_packet([0xAA; 6], [0xBB; 6], src_ipv6, dst_ipv6, 1, 17);
        let reply =
            generate_icmpv6_error(&original, Icmpv6Error::HopLimitExceeded, router_ip, "lan0")
                .unwrap();

        let ipv6_src = &reply.data[ETH_HEADER_LEN + 8..ETH_HEADER_LEN + 24];
        assert_eq!(ipv6_src, &router_ip);
    }

    #[test]
    fn all_error_types_produce_correct_type_code() {
        let src_ipv6 = [
            0x20, 0x01, 0x0d, 0xb8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0x64,
        ];
        let dst_ipv6 = [
            0x20, 0x01, 0x0d, 0xb8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0x02,
        ];

        let original = make_test_ipv6_packet([0xAA; 6], [0xBB; 6], src_ipv6, dst_ipv6, 64, 17);

        let cases = vec![
            (Icmpv6Error::HopLimitExceeded, 3u8, 0u8),
            (Icmpv6Error::NoRoute, 1, 0),
        ];

        for (error, expected_type, expected_code) in cases {
            let reply = generate_icmpv6_error(&original, error, ROUTER_IPV6, "eth0").unwrap();
            let icmpv6_start = ETH_HEADER_LEN + IPV6_HEADER_LEN;
            assert_eq!(
                reply.data[icmpv6_start], expected_type,
                "wrong ICMPv6 type for {:?}",
                error
            );
            assert_eq!(
                reply.data[icmpv6_start + 1],
                expected_code,
                "wrong ICMPv6 code for {:?}",
                error
            );
        }
    }

    #[test]
    fn large_packet_truncated_to_minimum_mtu() {
        // Build a packet larger than 1280 bytes to test truncation.
        let src_mac = [0xAA, 0xBB, 0xCC, 0xDD, 0xEE, 0xFF];
        let dst_mac = [0x00, 0x11, 0x22, 0x33, 0x44, 0x55];
        let src_ipv6 = [
            0x20, 0x01, 0x0d, 0xb8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0x64,
        ];
        let dst_ipv6 = [
            0x20, 0x01, 0x0d, 0xb8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0x02,
        ];

        let mut original = Vec::new();
        // Ethernet header
        original.extend_from_slice(&dst_mac);
        original.extend_from_slice(&src_mac);
        original.extend_from_slice(&[0x86, 0xDD]);
        // IPv6 header
        original.push(0x60);
        original.push(0x00);
        original.push(0x00);
        original.push(0x00);
        let payload_len: u16 = 1400;
        original.extend_from_slice(&payload_len.to_be_bytes());
        original.push(17); // UDP
        original.push(1); // hop limit
        original.extend_from_slice(&src_ipv6);
        original.extend_from_slice(&dst_ipv6);
        // Large payload
        original.extend_from_slice(&vec![0xAA; 1400]);

        let reply = generate_icmpv6_error(
            &original,
            Icmpv6Error::HopLimitExceeded,
            ROUTER_IPV6,
            "lan0",
        )
        .unwrap();

        // Total frame must not exceed Ethernet(14) + 1280 = 1294
        assert!(
            reply.data.len() <= ETH_HEADER_LEN + IPV6_MINIMUM_MTU,
            "ICMPv6 error packet must not exceed minimum IPv6 MTU: got {} bytes",
            reply.data.len()
        );

        // IPv6 payload length must be consistent.
        let ipv6_payload_len = u16::from_be_bytes([
            reply.data[ETH_HEADER_LEN + 4],
            reply.data[ETH_HEADER_LEN + 5],
        ]);
        assert_eq!(
            ipv6_payload_len as usize,
            reply.data.len() - ETH_HEADER_LEN - IPV6_HEADER_LEN
        );
    }
}
