//! ICMP error message generation for the ruster dataplane.
//!
//! When the router drops a packet due to TTL expiration or unreachable
//! destination, it should generate an ICMP error message back to the
//! original sender per RFC 792.
//!
//! RFC-REF: RFC 792
//! "The Internet Protocol is not designed to be absolutely reliable.
//! The purpose of these control messages is to provide feedback about
//! problems in the communication environment [...]"
//!
//! # Loop prevention
//!
//! RFC-REF: RFC 792
//! "No ICMP error messages are sent about ICMP error messages."
//! We suppress ICMP error generation when the original packet is itself
//! an ICMP message (protocol = 1) to prevent infinite loops.

/// ICMP error types that can be generated by the router.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum IcmpError {
    /// Time Exceeded: TTL expired in transit.
    ///
    /// RFC-REF: RFC 792 Section "Time Exceeded Message"
    /// Type = 11, Code = 0: time to live exceeded in transit.
    TtlExceeded,

    /// Destination Unreachable: network unreachable.
    ///
    /// RFC-REF: RFC 792 Section "Destination Unreachable Message"
    /// Type = 3, Code = 0: net unreachable.
    NetUnreachable,

    /// Destination Unreachable: host unreachable.
    ///
    /// RFC-REF: RFC 792 Section "Destination Unreachable Message"
    /// Type = 3, Code = 1: host unreachable.
    HostUnreachable,
}

impl IcmpError {
    /// Return the (type, code) pair for this ICMP error.
    fn type_code(&self) -> (u8, u8) {
        match self {
            IcmpError::TtlExceeded => (11, 0),
            IcmpError::NetUnreachable => (3, 0),
            IcmpError::HostUnreachable => (3, 1),
        }
    }
}

/// An ICMP reply packet ready for transmission.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct IcmpReply {
    /// The interface on which to transmit this reply (back towards the sender).
    pub egress_iface: String,
    /// The complete Ethernet frame (Ethernet + IPv4 + ICMP) to transmit.
    pub data: Vec<u8>,
}

// ── Constants ───────────────────────────────────────────────────────

/// Minimum Ethernet header size.
const ETH_HEADER_LEN: usize = 14;

/// Standard IPv4 header size (no options).
const IPV4_HEADER_LEN: usize = 20;

/// ICMP header size: type(1) + code(1) + checksum(2) + unused(4) = 8.
const ICMP_HEADER_LEN: usize = 8;

/// EtherType for IPv4.
const ETHERTYPE_IPV4: u16 = 0x0800;

/// IPv4 protocol number for ICMP.
const IP_PROTO_ICMP: u8 = 1;

/// Minimum original packet length needed to generate an ICMP error:
/// Ethernet(14) + IPv4(20) + 8 bytes of original payload.
const MIN_ORIGINAL_PACKET_LEN: usize = ETH_HEADER_LEN + IPV4_HEADER_LEN + 8;

/// TTL for generated ICMP error packets.
const ICMP_ERROR_TTL: u8 = 64;

// ── Public API ──────────────────────────────────────────────────────

/// Generate an ICMP error message in response to a dropped packet.
///
/// The generated packet includes:
/// - Swapped Ethernet MACs (reply goes back towards the sender)
/// - New IPv4 header (src = `router_ip`, dst = original src IP, TTL = 64)
/// - ICMP header (type/code from `error`, checksum computed, 4 unused bytes)
/// - Original IP header + first 8 bytes of original payload
///
/// RFC-REF: RFC 792
/// "Every ICMP error message includes the Internet header and at least
/// the first 8 data octets of the datagram that triggered the error."
///
/// Returns `None` if:
/// - The original packet is too short (< 42 bytes: 14 Ethernet + 20 IPv4 + 8 payload)
/// - The original packet is not IPv4
/// - The original packet is itself ICMP (loop prevention per RFC 792)
pub fn generate_icmp_error(
    original_packet: &[u8],
    error: IcmpError,
    router_ip: [u8; 4],
    egress_iface: &str,
) -> Option<IcmpReply> {
    // ── Validate original packet ────────────────────────────────────
    if original_packet.len() < MIN_ORIGINAL_PACKET_LEN {
        return None;
    }

    // Check EtherType is IPv4.
    let ethertype = u16::from_be_bytes([original_packet[12], original_packet[13]]);
    if ethertype != ETHERTYPE_IPV4 {
        return None;
    }

    // Extract original IPv4 header fields.
    let orig_ipv4 = &original_packet[ETH_HEADER_LEN..];
    let orig_ihl = ((orig_ipv4[0] & 0x0F) as usize) * 4;
    if orig_ihl < IPV4_HEADER_LEN {
        return None;
    }
    let orig_protocol = orig_ipv4[9];

    // RFC-REF: RFC 792
    // "No ICMP error messages are sent about ICMP error messages."
    // Suppress ICMP generation for any ICMP packet to prevent loops.
    if orig_protocol == IP_PROTO_ICMP {
        return None;
    }

    // Extract original source IP (this becomes the ICMP reply destination).
    let orig_src_ip: [u8; 4] = [orig_ipv4[12], orig_ipv4[13], orig_ipv4[14], orig_ipv4[15]];

    // ── Build the ICMP payload ──────────────────────────────────────
    // RFC-REF: RFC 792
    // "Internet Header + 64 bits of Original Data Datagram"
    // We include the original IP header + first 8 bytes of the original
    // transport payload.
    let orig_ip_header_and_payload_len = orig_ihl + 8;
    let avail = original_packet.len() - ETH_HEADER_LEN;
    let icmp_payload_len = orig_ip_header_and_payload_len.min(avail);
    let icmp_payload = &orig_ipv4[..icmp_payload_len];

    // ── Build the reply packet ──────────────────────────────────────
    let icmp_total_len = ICMP_HEADER_LEN + icmp_payload_len;
    let ipv4_total_len = (IPV4_HEADER_LEN + icmp_total_len) as u16;
    let total_frame_len = ETH_HEADER_LEN + IPV4_HEADER_LEN + icmp_total_len;

    let mut pkt = Vec::with_capacity(total_frame_len);

    // ── Ethernet header (swapped MACs) ──────────────────────────────
    // dst MAC = original src MAC (reply back to sender)
    pkt.extend_from_slice(&original_packet[6..12]);
    // src MAC = original dst MAC (our interface MAC)
    pkt.extend_from_slice(&original_packet[0..6]);
    // EtherType: IPv4
    pkt.extend_from_slice(&ETHERTYPE_IPV4.to_be_bytes());

    // ── IPv4 header ─────────────────────────────────────────────────
    let ipv4_start = pkt.len();
    pkt.push(0x45); // version=4, IHL=5
    pkt.push(0x00); // DSCP/ECN
    pkt.extend_from_slice(&ipv4_total_len.to_be_bytes());
    pkt.extend_from_slice(&[0x00, 0x00]); // identification
    pkt.extend_from_slice(&[0x00, 0x00]); // flags/fragment
    pkt.push(ICMP_ERROR_TTL);
    pkt.push(IP_PROTO_ICMP);
    pkt.extend_from_slice(&[0x00, 0x00]); // checksum placeholder
    pkt.extend_from_slice(&router_ip);
    pkt.extend_from_slice(&orig_src_ip);

    // Compute IPv4 header checksum.
    compute_ipv4_checksum(&mut pkt[ipv4_start..ipv4_start + IPV4_HEADER_LEN]);

    // ── ICMP header ─────────────────────────────────────────────────
    let (icmp_type, icmp_code) = error.type_code();
    let icmp_start = pkt.len();
    pkt.push(icmp_type);
    pkt.push(icmp_code);
    pkt.extend_from_slice(&[0x00, 0x00]); // checksum placeholder
    pkt.extend_from_slice(&[0x00, 0x00, 0x00, 0x00]); // 4 unused bytes

    // ── ICMP payload (original IP header + 8 bytes) ─────────────────
    pkt.extend_from_slice(icmp_payload);

    // Compute ICMP checksum over header + payload.
    compute_icmp_checksum(&mut pkt[icmp_start..]);

    Some(IcmpReply {
        egress_iface: egress_iface.to_string(),
        data: pkt,
    })
}

// ── Checksum helpers ────────────────────────────────────────────────

/// Compute and write the IPv4 header checksum in place.
fn compute_ipv4_checksum(hdr: &mut [u8]) {
    // Zero checksum field first.
    hdr[10] = 0x00;
    hdr[11] = 0x00;
    let cksum = internet_checksum(hdr);
    hdr[10] = (cksum >> 8) as u8;
    hdr[11] = (cksum & 0xFF) as u8;
}

/// Compute and write the ICMP checksum in place.
///
/// RFC-REF: RFC 792
/// "The checksum is the 16-bit ones's complement of the one's complement
/// sum of the ICMP message starting with the ICMP Type."
fn compute_icmp_checksum(icmp_msg: &mut [u8]) {
    // Zero checksum field (bytes 2-3).
    icmp_msg[2] = 0x00;
    icmp_msg[3] = 0x00;
    let cksum = internet_checksum(icmp_msg);
    icmp_msg[2] = (cksum >> 8) as u8;
    icmp_msg[3] = (cksum & 0xFF) as u8;
}

/// Compute the Internet checksum (RFC 1071) over a byte slice.
fn internet_checksum(data: &[u8]) -> u16 {
    let mut sum: u32 = 0;
    for i in (0..data.len()).step_by(2) {
        let word = if i + 1 < data.len() {
            u16::from_be_bytes([data[i], data[i + 1]])
        } else {
            u16::from_be_bytes([data[i], 0])
        };
        sum += word as u32;
    }
    while (sum >> 16) != 0 {
        sum = (sum & 0xFFFF) + (sum >> 16);
    }
    !(sum as u16)
}

// ── Tests ───────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    /// Helper: compute IPv4 header checksum and write it into the header.
    fn set_ipv4_checksum(hdr: &mut [u8]) {
        hdr[10] = 0x00;
        hdr[11] = 0x00;
        let mut sum: u32 = 0;
        for i in (0..hdr.len()).step_by(2) {
            let word = if i + 1 < hdr.len() {
                u16::from_be_bytes([hdr[i], hdr[i + 1]])
            } else {
                u16::from_be_bytes([hdr[i], 0])
            };
            sum += word as u32;
        }
        while (sum >> 16) != 0 {
            sum = (sum & 0xFFFF) + (sum >> 16);
        }
        let cksum = !(sum as u16);
        hdr[10] = (cksum >> 8) as u8;
        hdr[11] = (cksum & 0xFF) as u8;
    }

    /// Build a valid Ethernet + IPv4 + UDP packet for testing.
    fn make_test_packet(
        src_mac: [u8; 6],
        dst_mac: [u8; 6],
        src_ip: [u8; 4],
        dst_ip: [u8; 4],
        ttl: u8,
        protocol: u8,
    ) -> Vec<u8> {
        let mut pkt = Vec::new();
        // Ethernet header (14 bytes)
        pkt.extend_from_slice(&dst_mac);
        pkt.extend_from_slice(&src_mac);
        pkt.extend_from_slice(&[0x08, 0x00]); // EtherType IPv4

        // IPv4 header (20 bytes)
        let ipv4_start = pkt.len();
        pkt.push(0x45); // version=4, IHL=5
        pkt.push(0x00); // DSCP/ECN
        let total_len: u16 = 20 + 8; // IP header + 8 bytes payload
        pkt.extend_from_slice(&total_len.to_be_bytes());
        pkt.extend_from_slice(&[0x00, 0x00]); // identification
        pkt.extend_from_slice(&[0x00, 0x00]); // flags/fragment
        pkt.push(ttl);
        pkt.push(protocol);
        pkt.extend_from_slice(&[0x00, 0x00]); // checksum placeholder
        pkt.extend_from_slice(&src_ip);
        pkt.extend_from_slice(&dst_ip);

        set_ipv4_checksum(&mut pkt[ipv4_start..ipv4_start + 20]);

        // Minimal payload (8 bytes — e.g., UDP header)
        pkt.extend_from_slice(&[0x00, 0x50]); // src port: 80
        pkt.extend_from_slice(&[0x00, 0x51]); // dst port: 81
        pkt.extend_from_slice(&[0x00, 0x08]); // length: 8
        pkt.extend_from_slice(&[0x00, 0x00]); // checksum: 0

        pkt
    }

    /// Verify the IPv4 header checksum in a packet slice is valid.
    fn verify_ipv4_checksum(ipv4_header: &[u8]) -> bool {
        let mut sum: u32 = 0;
        for i in (0..ipv4_header.len()).step_by(2) {
            let word = if i + 1 < ipv4_header.len() {
                u16::from_be_bytes([ipv4_header[i], ipv4_header[i + 1]])
            } else {
                u16::from_be_bytes([ipv4_header[i], 0])
            };
            sum += word as u32;
        }
        while (sum >> 16) != 0 {
            sum = (sum & 0xFFFF) + (sum >> 16);
        }
        sum as u16 == 0xFFFF
    }

    /// Verify the ICMP checksum in a message slice is valid.
    fn verify_icmp_checksum(icmp_msg: &[u8]) -> bool {
        let mut sum: u32 = 0;
        for i in (0..icmp_msg.len()).step_by(2) {
            let word = if i + 1 < icmp_msg.len() {
                u16::from_be_bytes([icmp_msg[i], icmp_msg[i + 1]])
            } else {
                u16::from_be_bytes([icmp_msg[i], 0])
            };
            sum += word as u32;
        }
        while (sum >> 16) != 0 {
            sum = (sum & 0xFFFF) + (sum >> 16);
        }
        sum as u16 == 0xFFFF
    }

    // ── TTL Exceeded tests ──────────────────────────────────────────

    #[test]
    fn ttl_exceeded_generates_icmp() {
        let src_mac = [0xAA, 0xBB, 0xCC, 0xDD, 0xEE, 0xFF];
        let dst_mac = [0x00, 0x11, 0x22, 0x33, 0x44, 0x55];
        let src_ip = [192, 168, 1, 100];
        let dst_ip = [8, 8, 8, 8];
        let router_ip = [192, 168, 1, 1];

        let original = make_test_packet(src_mac, dst_mac, src_ip, dst_ip, 1, 17);
        let reply = generate_icmp_error(&original, IcmpError::TtlExceeded, router_ip, "lan0")
            .expect("should generate ICMP reply");

        assert_eq!(reply.egress_iface, "lan0");

        let data = &reply.data;

        // Check Ethernet header: MACs are swapped.
        assert_eq!(&data[0..6], &src_mac); // dst = original src
        assert_eq!(&data[6..12], &dst_mac); // src = original dst
        assert_eq!(&data[12..14], &[0x08, 0x00]); // EtherType IPv4

        // Check IPv4 header.
        let ipv4 = &data[ETH_HEADER_LEN..ETH_HEADER_LEN + IPV4_HEADER_LEN];
        assert_eq!(ipv4[0], 0x45); // version=4, IHL=5
        assert_eq!(ipv4[8], ICMP_ERROR_TTL); // TTL = 64
        assert_eq!(ipv4[9], IP_PROTO_ICMP); // protocol = ICMP
        assert_eq!(&ipv4[12..16], &router_ip); // src = router IP
        assert_eq!(&ipv4[16..20], &src_ip); // dst = original src IP

        // Check ICMP header.
        let icmp_start = ETH_HEADER_LEN + IPV4_HEADER_LEN;
        assert_eq!(data[icmp_start], 11); // Type: Time Exceeded
        assert_eq!(data[icmp_start + 1], 0); // Code: 0

        // ICMP payload should contain original IP header + 8 bytes.
        let icmp_payload_start = icmp_start + ICMP_HEADER_LEN;
        let expected_payload = &original[ETH_HEADER_LEN..ETH_HEADER_LEN + 28];
        assert_eq!(
            &data[icmp_payload_start..icmp_payload_start + 28],
            expected_payload
        );
    }

    #[test]
    fn net_unreachable_generates_icmp() {
        let original =
            make_test_packet([0xAA; 6], [0xBB; 6], [10, 0, 0, 5], [172, 16, 0, 1], 64, 17);
        let router_ip = [10, 0, 0, 1];

        let reply = generate_icmp_error(&original, IcmpError::NetUnreachable, router_ip, "wan0")
            .expect("should generate ICMP reply");

        let icmp_start = ETH_HEADER_LEN + IPV4_HEADER_LEN;
        assert_eq!(reply.data[icmp_start], 3); // Type: Destination Unreachable
        assert_eq!(reply.data[icmp_start + 1], 0); // Code: Net Unreachable
        assert_eq!(reply.egress_iface, "wan0");
    }

    #[test]
    fn host_unreachable_generates_icmp() {
        let original =
            make_test_packet([0xAA; 6], [0xBB; 6], [10, 0, 0, 5], [10, 0, 0, 99], 64, 17);
        let router_ip = [10, 0, 0, 1];

        let reply = generate_icmp_error(&original, IcmpError::HostUnreachable, router_ip, "wan0")
            .expect("should generate ICMP reply");

        let icmp_start = ETH_HEADER_LEN + IPV4_HEADER_LEN;
        assert_eq!(reply.data[icmp_start], 3); // Type: Destination Unreachable
        assert_eq!(reply.data[icmp_start + 1], 1); // Code: Host Unreachable
    }

    // ── Loop prevention tests ───────────────────────────────────────

    #[test]
    fn no_icmp_for_icmp_packets() {
        // RFC-REF: RFC 792
        // "No ICMP error messages are sent about ICMP error messages."
        let original = make_test_packet(
            [0xAA; 6],
            [0xBB; 6],
            [192, 168, 1, 100],
            [8, 8, 8, 8],
            1,
            1, // protocol = ICMP
        );

        let result =
            generate_icmp_error(&original, IcmpError::TtlExceeded, [192, 168, 1, 1], "lan0");
        assert!(
            result.is_none(),
            "should not generate ICMP for ICMP packets"
        );
    }

    // ── Short packet tests ──────────────────────────────────────────

    #[test]
    fn no_icmp_for_short_packets() {
        // Packet shorter than minimum (14 + 20 + 8 = 42 bytes).
        let short_pkt = vec![0u8; 30];
        let result =
            generate_icmp_error(&short_pkt, IcmpError::TtlExceeded, [192, 168, 1, 1], "lan0");
        assert!(
            result.is_none(),
            "should not generate ICMP for short packets"
        );
    }

    #[test]
    fn no_icmp_for_exactly_too_short() {
        // Packet of exactly 41 bytes (1 byte short of minimum).
        let pkt = vec![0u8; MIN_ORIGINAL_PACKET_LEN - 1];
        let result = generate_icmp_error(&pkt, IcmpError::NetUnreachable, [10, 0, 0, 1], "eth0");
        assert!(result.is_none());
    }

    // ── Non-IPv4 tests ──────────────────────────────────────────────

    #[test]
    fn no_icmp_for_non_ipv4() {
        // ARP packet (EtherType = 0x0806).
        let mut pkt = Vec::new();
        pkt.extend_from_slice(&[0xFF; 6]); // dst
        pkt.extend_from_slice(&[0xAA; 6]); // src
        pkt.extend_from_slice(&[0x08, 0x06]); // EtherType: ARP
        pkt.extend_from_slice(&[0x00; 28]); // ARP payload

        let result = generate_icmp_error(&pkt, IcmpError::TtlExceeded, [192, 168, 1, 1], "lan0");
        assert!(
            result.is_none(),
            "should not generate ICMP for non-IPv4 packets"
        );
    }

    // ── Checksum tests ──────────────────────────────────────────────

    #[test]
    fn icmp_reply_has_valid_ipv4_checksum() {
        let original = make_test_packet(
            [0xAA; 6],
            [0xBB; 6],
            [192, 168, 1, 100],
            [8, 8, 8, 8],
            1,
            17,
        );
        let reply =
            generate_icmp_error(&original, IcmpError::TtlExceeded, [192, 168, 1, 1], "lan0")
                .unwrap();

        let ipv4_header = &reply.data[ETH_HEADER_LEN..ETH_HEADER_LEN + IPV4_HEADER_LEN];
        assert!(
            verify_ipv4_checksum(ipv4_header),
            "IPv4 header checksum should be valid"
        );
    }

    #[test]
    fn icmp_reply_has_valid_icmp_checksum() {
        let original = make_test_packet(
            [0xAA; 6],
            [0xBB; 6],
            [192, 168, 1, 100],
            [8, 8, 8, 8],
            1,
            17,
        );
        let reply =
            generate_icmp_error(&original, IcmpError::TtlExceeded, [192, 168, 1, 1], "lan0")
                .unwrap();

        let icmp_start = ETH_HEADER_LEN + IPV4_HEADER_LEN;
        let icmp_msg = &reply.data[icmp_start..];
        assert!(
            verify_icmp_checksum(icmp_msg),
            "ICMP checksum should be valid"
        );
    }

    // ── Router IP tests ─────────────────────────────────────────────

    #[test]
    fn icmp_reply_uses_provided_router_ip() {
        let router_ip = [10, 99, 88, 77];
        let original = make_test_packet(
            [0xAA; 6],
            [0xBB; 6],
            [192, 168, 1, 100],
            [8, 8, 8, 8],
            1,
            17,
        );

        let reply =
            generate_icmp_error(&original, IcmpError::TtlExceeded, router_ip, "lan0").unwrap();

        let ipv4_src = &reply.data[ETH_HEADER_LEN + 12..ETH_HEADER_LEN + 16];
        assert_eq!(ipv4_src, &router_ip);
    }

    // ── Frame structure tests ───────────────────────────────────────

    #[test]
    fn icmp_reply_total_length_is_correct() {
        let original = make_test_packet(
            [0xAA; 6],
            [0xBB; 6],
            [192, 168, 1, 100],
            [8, 8, 8, 8],
            1,
            17,
        );
        let reply =
            generate_icmp_error(&original, IcmpError::TtlExceeded, [192, 168, 1, 1], "lan0")
                .unwrap();

        // Expected: Ethernet(14) + IPv4(20) + ICMP header(8) + orig IP header(20) + 8 bytes
        let expected_len = ETH_HEADER_LEN + IPV4_HEADER_LEN + ICMP_HEADER_LEN + 20 + 8;
        assert_eq!(reply.data.len(), expected_len);

        // Check IPv4 total length field.
        let ipv4_total_len = u16::from_be_bytes([
            reply.data[ETH_HEADER_LEN + 2],
            reply.data[ETH_HEADER_LEN + 3],
        ]);
        assert_eq!(
            ipv4_total_len as usize,
            IPV4_HEADER_LEN + ICMP_HEADER_LEN + 20 + 8
        );
    }

    #[test]
    fn icmp_reply_unused_bytes_are_zero() {
        let original = make_test_packet(
            [0xAA; 6],
            [0xBB; 6],
            [192, 168, 1, 100],
            [8, 8, 8, 8],
            1,
            17,
        );
        let reply =
            generate_icmp_error(&original, IcmpError::TtlExceeded, [192, 168, 1, 1], "lan0")
                .unwrap();

        // The 4 "unused" bytes after the ICMP checksum should all be zero.
        let icmp_start = ETH_HEADER_LEN + IPV4_HEADER_LEN;
        assert_eq!(
            &reply.data[icmp_start + 4..icmp_start + 8],
            &[0x00, 0x00, 0x00, 0x00]
        );
    }

    #[test]
    fn all_error_types_produce_correct_type_code() {
        let original = make_test_packet(
            [0xAA; 6],
            [0xBB; 6],
            [192, 168, 1, 100],
            [8, 8, 8, 8],
            64,
            17,
        );

        let cases = vec![
            (IcmpError::TtlExceeded, 11u8, 0u8),
            (IcmpError::NetUnreachable, 3, 0),
            (IcmpError::HostUnreachable, 3, 1),
        ];

        for (error, expected_type, expected_code) in cases {
            let reply = generate_icmp_error(&original, error, [10, 0, 0, 1], "eth0").unwrap();
            let icmp_start = ETH_HEADER_LEN + IPV4_HEADER_LEN;
            assert_eq!(
                reply.data[icmp_start], expected_type,
                "wrong ICMP type for {:?}",
                error
            );
            assert_eq!(
                reply.data[icmp_start + 1],
                expected_code,
                "wrong ICMP code for {:?}",
                error
            );
        }
    }
}
